baseURL = 'https://simoat.work/'
languageCode = 'en-us'
title = 'SimoAt.Work'
theme = 'archie'

googleAnalytics = 'G-N70242LL82'

[params]
author = "Simone Di Maulo"
mode="toggle" # color-mode â†’ light,dark,toggle or auto
useCDN=false # don't use CDNs for fonts and icons, instead serve them locally.
subtitle = "I like code, sw architecture and helping developers work better"
mathjax = false # enable MathJax support
katex = false # enable KaTeX support
customcss = ["/css/custom.css", '/css/fonts.css']

# Social
[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/simodima"

# Main menu Items
[[menu.main]]
name = "home"
url = "/"
weight = 1
